
version: '2'
services:
    todolist:
        build: ./todolist
        volumes: 
            - ./todolist:/app
        ports:
            - "5000:80"

             
    bot:
        build: ./bot
        volumes:
            - ./bot:/app
        ports:
            - "5001:80"
        links:
            - todolist
           
